#!/bin/bash

echo "📊 Monitoring Certificate Email Delivery"
echo "========================================"
echo ""
echo "🎯 This will monitor the application logs for certificate email delivery"
echo "📧 After you approve a certificate request, watch for email delivery status"
echo ""
echo "🔍 Key log messages to look for:"
echo "   ✅ 'Successfully generated certificate for request...'"
echo "   📧 'Attempting to email certificate for request...'"
echo "   📦 'Using provided certificate data...'"
echo "   🔒 'Using provided CA certificate...'"
echo "   📤 'Certificate email sent successfully...'"
echo ""
echo "❌ Error messages to watch for:"
echo "   'Failed to send certificate email'"
echo "   'Certificate or private key data missing'"
echo "   'CA certificate not provided'"
echo "   'Failed to get P12 certificate'"
echo ""
echo "📋 Instructions:"
echo "1. Leave this running in a terminal"
echo "2. In another window, go to https://ca.bonner.com"
echo "3. Navigate to the dashboard and approve a pending certificate"
echo "4. Watch this terminal for email delivery logs"
echo ""
echo "Press Ctrl+C to stop monitoring"
echo "========================================"
echo ""

# Monitor logs with filtering for relevant messages
docker logs ca-manager-f-web-interface-1 --follow --tail 5 | grep -E "(email|certificate|Certificate|P12|SMTP|send|sent|failed)"