name: 🐛 Bug Report
description: Report a bug or issue with CA Manager
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following information to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have reviewed the documentation and troubleshooting guide
          required: true
        - label: This is not a security vulnerability (use security@camanager.dev instead)
          required: true

  - type: dropdown
    id: version
    attributes:
      label: CA Manager Version
      description: Which version of CA Manager are you using?
      options:
        - "4.0.0"
        - "3.1.2"
        - "3.1.1" 
        - "3.1.0"
        - "3.0.0"
        - "Other (specify in description)"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - "Web Interface"
        - "Setup Wizard"
        - "SCEP Server"
        - "OCSP Responder"
        - "OCSP Simulator" 
        - "iOS SCEP Simulator"
        - "Database/PostgreSQL"
        - "Traefik/Routing"
        - "Docker/Deployment"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Ubuntu 20.04"
        - "Ubuntu 22.04"
        - "Debian 11"
        - "Debian 12"
        - "CentOS 7"
        - "CentOS 8"
        - "RHEL 8"
        - "RHEL 9"
        - "macOS Monterey"
        - "macOS Ventura"
        - "macOS Sonoma"
        - "Windows 10"
        - "Windows 11"
        - "Other (specify in additional context)"

  - type: input
    id: docker-version
    attributes:
      label: Docker Version
      description: Output of `docker --version`
      placeholder: "Docker version 24.0.7, build afdd53b"
    validations:
      required: true

  - type: input
    id: docker-compose-version
    attributes:
      label: Docker Compose Version
      description: Output of `docker-compose --version`
      placeholder: "Docker Compose version v2.21.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser (if web interface issue)
      description: Which browser are you using?
      options:
        - "Not applicable"
        - "Chrome/Chromium"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Other"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      render: shell
      placeholder: |
        # Docker logs
        docker-compose logs web-interface
        
        # Or specific service logs
        docker-compose logs scep-server

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive data)
      render: yaml
      placeholder: |
        # .env file (sanitized)
        DOMAIN=example.com
        AUTHENTICATION_ENABLED=true
        
        # Or docker-compose.yml sections

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, error messages, network configuration, etc.

  - type: checkboxes
    id: support
    attributes:
      label: Support Options
      description: How can we help you?
      options:
        - label: I would like to contribute a fix for this issue
        - label: I can provide additional testing if needed
        - label: I have a workaround I can share
        - label: This is blocking my production deployment